### ISSUE TITLE
Meldinger fungerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#132]
Meldinger vises ikke ved oppstart og man får ikke lagt til nye heller

https://forsiden.portalen.t-fk.no/api/messages?roles=alle|administrasjonen|sentraladministrasjonen&limit=10 kan ha noe med saken å gjøre?

**Comment by gerhardsletten** [comment]
Tror dette er kombinasjon av flere problemer, dere må jo bruke wss og ikke ws protokollen når dere kjører ssl på resten. Så at enviroment variabelen for det ikke når klient-side scriptet, så har pusher en oppdatering som setter wss som standard i prod.

At ikke meldinger blir lastet initelt har ikke noe med websocket å gjøre da, siden det bare brukes for oppdateringer underveis i session, så lurer på om feil #139 kan være et problem (har blitt fikset). Har også [installert mongo-search-plugin](https://github.com/telemark/portalen-forside/blob/master/package.json#L129), for å åpne for at søketjenesten deres kan søke i meldinger også, og tror kanskje man må fjerne gamle dokumenter i collectionen, siden pluginet legger på noen ekstra felter, og at det kan skape noen feil når de eldre dokumentene ikke har dem.

**Comment by zrrrzzt** [comment]
@maccyber nuker du meldingsbasen så ser vi om det hjelper?

**Comment by Tmholen** [comment]
Meldingene kommer ikke frem automatisk. Du må oppdatere siden for å se dem.

**Comment by gerhardsletten** [comment]
Tror denne skal være fikset nå som ws funker
