### ISSUE TITLE
Ikke vis igjen - fungerer ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#133]
Trykker "Ikke vis igjen" på en av artiklene på forsiden, men ikke noe skjer.

**Comment by gerhardsletten** [comment]
Får du noen feilmelding i nettleser-konsollen? Sjekk også network tabben i chrome, det skal gå et DELETE request til /api/info

Er det noe mulighet for at jeg kunne fått en login til live-løsningen?

**Comment by zrrrzzt** [comment]
tror du har fått en bruker til live, sender info påny i Gitter

**Comment by gerhardsletten** [comment]
Denne virker for meg nå, kan noen andre sjekke

**Comment by zrrrzzt** [comment]
Funket på annonser og artikler for meg også
