### ISSUE TITLE
Mer tilpasset visning av annonser.

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#134]
Er det mulig å tilpasse visningen av annonser etter det som er publisert?

Hvis du embedder noe med en fast størrelse, som ikke går an å endre til prosentstørrelse, så blir det seende veldig rart ut. Innholdet blir liggende til venstre, mens det blir en stor hvit boks som dekker resten av skjermen.

**Comment by gerhardsletten** [comment]
Kunne du publisert noen flere varianter så jeg kan få så / justert for det? Tidligere idag var det kun en annonse med et htmlContent som var en bilde inne i en p-tag.

**Comment by Tmholen** [comment]
Ja, det skal jeg ordne

**Comment by gerhardsletten** [comment]
Ok, forsøkt å gjøre noe med det, men synes kanskje det er litt rotete med flere måter å vise annonser på, synes datakilden burde hatt et felt for html-innholdet som skal vises, på en av de som ligger inne nå, så er matrixcontent listen tom, og jeg ser det istede ligger en iframe i description feltet. 

Men f eks den facebook page-widgeten får veldig mye whitespace på høyresiden når annonse ligger slik tvergående. Vet ikke om vi har tid til å utforske noe mer nå, men har iallefall lagt inn en style for at iframe inne i annonsene også streker seg over hele bredden, men gjør ikke noe med høyden. 

Dere kan løse det i feltet i wordpress der dere legger inn annonseinnholdet selv også ved å også med [fluid video teknikken](https://css-tricks.com/NetMag/FluidWidthVideo/Article-FluidWidthVideo.php) på html-innholdet dere sender over.
