### ISSUE TITLE
Log ut funker ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#135]

**Comment by zrrrzzt** [comment]
Spesifiserer denne: Funker om jeg logger meg ut med en gang
funker ikke om man gjør litt er innom andre tabs og så kommer tilbake

**Comment by zrrrzzt** [comment]
overse denne til jeg klarer å gjenskape feilen

**Comment by gerhardsletten** [comment]
Så man tidligere fikk en feilmelding når man logget seg ut, pga at en komponent abonnerte på noe data, som da ble slettet. Men skal være fikset, så kan være du hadde en cachet versjon i innlogget sesjon som førte til dette. Greit å gå inn i cookies og tømme dem å gjøre en clean innlogging for å sjekke.

**Comment by gerhardsletten** [comment]
Ser ut som denne er i ordent nå, så lukker
