### ISSUE TITLE
Forstørrelsesglasset er ikke klikkbart

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#137]
Mange vil nok tro at de skal klikke på forstørrelsesglasset når de har skrevet inn søketeksten. Den fungerer ikke nå. Mulig det har sammenheng med at søket ikke fungerer.

**Comment by gerhardsletten** [comment]
> Mulig det har sammenheng med at søket ikke fungerer.

Hvis søket ikke fungerer så fungerer nok ikke søkeknappen heller. Er dette noe i oppsettet deres, eller noe jeg skal se på?

**Comment by Tmholen** [comment]
Søket fungerer igjen, det var nok en midlertidig feil hos meg. Men det er fortsatt ikke mulig å trykke på forstørrelsesglasset for å søke. Bare enter-knappen.
