### ISSUE TITLE
Meldinger fryser siden

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#138]
Hvis du skriver inn en melding og velger enten avbryt eller lagre og kommer tilbake til forsiden så har hele siden "fryst". Det er umulig å scrolle noe mer. Man må da oppdatere siden for å få det til. Noen ganger blir man også logget ut og må logge seg inn igjen.

**Comment by gerhardsletten** [comment]
Ser ut som dette ikke lenger er et problem i forhold til meldingene. De fungerer å laste initelt

**Comment by Tmholen** [comment]
Dette er fortsatt et problem hos meg. Når jeg har skrevet en melding, evt valgt å avbryte så fryser fortsatt siden. Man er da nødt til å refreshe den.

**Comment by gerhardsletten** [comment]
Ok, testet ikke å avbryte..

**Comment by Tmholen** [comment]
Jeg får det både når jeg lager en melding og trykker lagre, og når jeg trykker avbryt.

**Comment by gerhardsletten** [comment]
Ser ut som det blir hengene igjen en overflow:hidden på body-taggen, når lightbox lukkes som gjør at man ikke får skrollet. Sjekker opp

**Comment by gerhardsletten** [comment]
Skulle egentlig være fikset i react-toolbox i følge denne [#532](https://github.com/react-toolbox/react-toolbox/issues/532)
