### ISSUE TITLE
Meldinger: ekspandert meny forsvinner ikke

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#142]
Nettleser: Chrome

Testcase: 
trykk på ekspanderende meny (de tre prikkene) på den øverste meldingen
dersom man ikke utfører noen av valgene forvinner ikke menyen. selv om man trykker andre steder på siden

Løsning: Ha et lukk valg i den ekspanderende menyen og sørg for at den lukkes om man trykke andre steder

**Comment by gerhardsletten** [comment]
Kan det være at du allerede er i en låst modus pga andre feil. Skjer det f eks hvis du refresher siden og gjentar?
