### ISSUE TITLE
Meldinger: feil ikoner

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#144]
Iflg pocen vi satt opp skal meldinger ha 2 ikoner på forsiden pin og slett (dvs ikke vis mer utgaven av slett)

nå er det et hjerte der og ekspanderende meny

**Comment by gerhardsletten** [comment]
Altså at slett / ikke vis mer flyttes ut av dropdown?

Fant ikke noe fylt / ikke flyt variasjon av "pin" symbol i [material icons listen her](https://design.google.com/icons/), så derfor valgte jeg hjerte, selv om det kan bli litt "teenage aktig".

Kunne vi brukt star ikonet istede, siden det har en outlinet variant og en fylt versjon:

![image](https://cloud.githubusercontent.com/assets/63344/16302956/367068f4-394e-11e6-97c2-b3c471f19ecb.png)

**Comment by Tmholen** [comment]
Ja, ikke vis mer kan flyttes ut av dropdown. Og hvis pin bare finnes i fylt versjon så kan vi beholde hjertet synes jeg. Det er litt mer intuitivt og får kanskje noen byråkrater til å føle seg unge.

**Comment by gerhardsletten** [comment]
Ok, da beholder vi hjertene men flytter skjult ut

**Comment by zrrrzzt** [comment]
den er grei
