### ISSUE TITLE
Meldinger. Får ikke favorite en melding.

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#145]
Når jeg prøver å bruke knappen for å favorite en melding så ser det ikke ut til å fungere. Den bare blinker, men blir ikke markert.

**Comment by gerhardsletten** [comment]
Dette henger også sammen med at ws ikke virker, siden man pusher oppdatert melding tilbake til bruker via ws. Forsøker du å laste siden på nytt ser du at meldinger er merket som likt. Så per def er ikke dette en bug..
