### ISSUE TITLE
Velger jeg "ny/endre" på meldinger forsvinner skrollbar

### ISSUE THREAD

**Issue by maccyber** [telemark/portalen-forside#146]
![endre](https://cloud.githubusercontent.com/assets/701351/16302244/53728422-394a-11e6-8d23-f25adbfb5b87.png)

Velger jeg "ny melding" eller "endre" på meldinger forsvinner vertikal- skrolle mulighetene, og jeg må refreshe siden for å komme tilbake til toppen.

Testet i chrome

**Comment by gerhardsletten** [comment]
Dette var samme bug som #138 og er fikset nå
