### ISSUE TITLE
Oppgaver vises ikke i mobilvisning 

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#149]
Hos meg blir oppgavene borte i mobilvisning. Er ikke noe mer etter meldinger.

**Comment by zrrrzzt** [comment]
hos meg ser alt smooth ut på mobil. nexux 6, android

**Comment by Tmholen** [comment]
Ikke på iPhone 6.

**Comment by Tmholen** [comment]
Rettelse: Oppgaver og meldinger har lagt seg oppå hverandre ser det ut til.

**Comment by maccyber** [comment]
![image](https://cloud.githubusercontent.com/assets/701351/16329687/2e47271c-39e4-11e6-8659-23c77682df8e.png)
