### ISSUE TITLE
Scrolling i venstremenyen blir kutta

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#158]
Scrollingen i venstremenyen dekker ikke hele siden, men blir kutta litt nede på siden.

![feil i meny](https://cloud.githubusercontent.com/assets/8641408/16374580/638fd9b2-3c57-11e6-9773-117c2d9d598b.jpg)

**Comment by gerhardsletten** [comment]
React-toolbox bruker endel flex-box som er [ganske godt støtta nå](http://caniuse.com/#feat=flexbox), men IE henger som vanlig litt etter. Er dette fra IE (skrollbarene ser litt ie-aktige ut).

**Comment by Tmholen** [comment]
Nei, det er faktisk fra chrome. Får det samme i Firefox. I IE ser faktisk hele siden slik ut 
![image](https://cloud.githubusercontent.com/assets/8641408/16406823/c80dd754-3d10-11e6-8d42-c786b619bfc8.png)

Det har den ikke gjort før.
