### ISSUE TITLE
Sette roller/grupper på bakgrunn av company 

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#16]
Ta company fra brukeren etter ldap-innlogging og kjør denne gjennom https://github.com/telemark/portalen-roles for å få gruppene vedkommende tilhører

```
seneca.act({"cmd": "map-roles", "type": "user", "company": "Bø vidaregåande skule"}, (error, data) => {})
```

**Comment by gerhardsletten** [comment]
Ok, hvis jeg skal kjøre denne seneca lokalt for utvikling, så tror jeg det fungerer dårlig med å kjøre hele applikasjonen inne i docker. Må jeg da bare sjekke ut de andre mikroservicene og kjøre de lokalt samtidig?

**Comment by zrrrzzt** [comment]
Jeg har alle kjørende i hvert sitt vindu lokalt ja

**Comment by gerhardsletten** [comment]
Denne skal være fikset i versjonen tidligere idag, så lukker
