### ISSUE TITLE
Fikse meldingstjenesten

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#17]
Det er ikke foreløpig ikke mulig å legge ut meldinger. De forsvinner når vi trykker på lagre.

**Comment by gerhardsletten** [comment]
Eksponerer dere api-serveren (port 3030) utad? Fikk ikke til å kjøre proxy på ws, så frontend må ha mulighet for å kommunisere med den.

Sjekk console i chrome for om det er noen feilmeldinger.

**Comment by zrrrzzt** [comment]
@maccyber her må du trå til å svare litt

**Comment by zrrrzzt** [comment]
Tipper dette er problemet @gerhardsletten 

```
client.js:200Mixed Content: The page at 'https://forsiden.portalen.t-fk.no/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://forsiden.portalen.t-fk.no:3030/'. This request has been blocked; this endpoint must be available over WSS.s._connect @ client.js:200
client.js:200Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```
