### ISSUE TITLE
Forslagskasse

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#18]
Som nevnt i e-post i går:
I den versjonen vi laget selv tidligere var det en forslagskasse. Se her: https://slusen.t-fk.no/feedback I en av de første versjonen var den med, men uten funksjonalitet. Kan du sette opp den igjen. Du kan lage skjemaet og bruke send inn kode

**Comment by gerhardsletten** [comment]
Jepp, men er det denne servicen i github-api'et den skal sende til:
`https://developer.github.com/v3/issues/#create-an-issue`

**Comment by zrrrzzt** [comment]
Her er koden vi brukte for innsending https://github.com/telemark/portalen/blob/master/handlers/feedback.js og settings er denne process.env.GITHUB_FEEDBACK_URL = 'https://api.github.com/repos/telemark/feedback/issues'
