### ISSUE TITLE
Peker over shortcuts

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#19]
Når du holder pekeren over shortcuts (fagsystemer) så burde den bli til en pekende hånd som er litt mer vanlig for å signalisere at noe er klikkbart.

**Comment by gerhardsletten** [comment]
Trodde egentlig det ville blitt mye krøll med at jeg måtte resette stiler hvis jeg la en lenke rundt boksen, men testet litt lokalt, og ser at går bra så lenge jeg resetter farge, underline. Så da løser jeg det heller med en lenke rundt, så får man mus-peker.
