### ISSUE TITLE
Bytt fra Express til Hapi

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#3]
Er en lignende startpakke som den du har brukt, men for Hapi her https://github.com/luandro/hapi-universal-redux

**Comment by gerhardsletten** [comment]
Brukte litt tid i starten av prosjektet på både den og [https://github.com/Dindaleon/hapi-react-starter-kit](https://github.com/Dindaleon/hapi-react-starter-kit)

Den du nevnte hadde veldig mye på kryss og tvers, som gjorde det litt vanskelig å forstå hva alt gjorde, og i den andre så sleit jeg litt med skjønne hvordan jeg skulle få til å dele "session" mellom server og klient. Det var derfor jeg tenkte at for å være litt produktiv så må jeg begynne i et kjent miljø..

Har begynt på det nå sjekk egen hapi-branch. Er ikke like kjent med hapi, så kunne du gitt noen innspill, se [commit her](https://github.com/telemark/portalen-forside/commit/5394a00426c72031456d2cbde4a50e7880935d3d)

* `api/api.js` kjører som en egen server, og `src/server.js` skal videresende `/api` request til den, lar det seg gjøre i Hapi? Har satt opp noen proxy-routes med [h2o2 her](https://github.com/telemark/portalen-forside/blob/HapiJS/src/server.js#L37) Og vil det fungere for med websockets?
* Hvordan løser man "middleware" i hapi, har en [funksjon her](https://github.com/telemark/portalen-forside/blob/HapiJS/api/routes/user.js#L37) som i express-sammenhent kan puttes før en routehandler, og som stopper requesten om brukeren ikke har en gyldig session.

**Comment by zrrrzzt** [comment]
Jeg er ganske blank på Express så kan bare henvise deg til googling på hovedforskjellene på Hapi og Express. Litt info er her http://stackoverflow.com/questions/30469767/how-do-express-and-hapi-compare-to-each-other. Hapi baserer seg mye på konfigurasjon og utvider funksjonalitet vha plug-ins.

Flere porter på samme server løser du vha connections i Hapi http://stackoverflow.com/questions/31886099/multiple-connections-on-a-hapi-server

Ang deling av session osv ser det ut til at https://github.com/Dindaleon/hapi-react-starter-kit kanskje er nærmest det du skal lage for oss og spesielt her https://github.com/Dindaleon/hapi-react-starter-kit/blob/master/src/config.js gjøres mye av oppsettet for jwt og redirect ved ugyldig session er gjort her https://github.com/Dindaleon/hapi-react-starter-kit/blob/master/src/routes.js

Websockets på hapi hadde jeg sett for meg at ble løst av hapines https://github.com/hapijs/nes

https://github.com/telemark/portalen innholder all grunnfunksjonalitet men den er da med trad. handlebars i stedet for react/redux
