### ISSUE TITLE
Få annonser til å fungere

### ISSUE THREAD

**Issue by Tmholen** [telemark/portalen-forside#47]
Visningen for annonser fungerer ikke veldig bra. Det er bare en veldig stor hvit firkant. I tillegg viser den ikke noe html-content, men bare tittel. Det vi ønsket er det motsatte, ref. denne posten på Gitter: https://gitter.im/telemark/portalen-devops?at=5729d71212cceadb7b1a7e06.

**Comment by gerhardsletten** [comment]
Kunne dere publisert  noen annonser og nyheter så jeg kan få sjekket visningen etter at disse har blitt koblet til api? Kanskje data-feltene har endret seg?

**Comment by Tmholen** [comment]
Ja, nå ligger det et par ute.

**Comment by gerhardsletten** [comment]
Under hvilke roller er de publisert? Får de ikke opp..

**Comment by zrrrzzt** [comment]
De er litt utilgjengelige akkurat nå. Holder på å flytte alle løsningene til ny server. Kan si fra på Gitter når det er opp igjen

**Comment by gerhardsletten** [comment]
@zrrrzzt Er servicen for dette fikset nå? Og for hvilke bruker kan jeg få noe data? `/api/content/gasg?roles=all` gir ingen artikler eller annonser..

**Comment by zrrrzzt** [comment]
@Tmholen er på saken ang servicen

**Comment by Tmholen** [comment]
@gerhardsletten har du fast ip-adresse? Da kan leverandøren legge gjøre den servicen åpen for deg.

**Comment by gerhardsletten** [comment]
Hei, min ip idag er: 51.175.214.1

Men skal ikke service-systemet med seneca sørge for at dataene blir levert? Får jo data fra de andre mikroservicene

**Comment by zrrrzzt** [comment]
Seneca-servicene går mot ulike systemer. De når åpenbart de som kjøres herfra huset (oppgaver osv), men ikke de som er sperret (artikler og annonser)

**Comment by gerhardsletten** [comment]
Ok, si ifra når det er åpnet for meg da, så skal jeg sjekke ut denne issuen

**Comment by Tmholen** [comment]
De skal ha åpnet for deg, men si fra hvis det ikke er skjedd så skal jeg purre dem opp.

**Comment by gerhardsletten** [comment]
Får fortsatt ikke noe:

![image](https://cloud.githubusercontent.com/assets/63344/16246924/ad6347c6-3807-11e6-97bc-6156a5a635d4.png)

**Comment by zrrrzzt** [comment]
når du http://dev.telemarkportalen.vpdev.no/artikler.json @gerhardsletten ? Gir den resultat?

**Comment by Tmholen** [comment]
@gerhardsletten den @zrrzzt viser skal være åpnet for ip-adressen du ga i går. Jeg har vært i kontakt med leverandøren nå på morgenen.

**Comment by gerhardsletten** [comment]
Ja, da fikk jeg det opp. Muligens var det det noe med hvilke element i matrix-listen for annonser som feil, for jeg hadde tatt høyde for at det skulle være nr 2 i listen som skulle vises, ellers falt den tilbake på en standard artikkelvisning, men nå viser jeg altså siste htmlContent element i matrixlisten, og da kommer iallefall den annonsen som ligger inne opp. Tror det altså skal være fikset nå. Lukker denne saken nå.

Har også satt opp en egen route som kan kobles på søketjenesten deres, den ligger eksponert nå på api-serveren, så intern adresse er:

http://localhost:3030/messages/search?query=<søkeord>&roles=<kommaseparert liste>&size=1&offset=1&userId=<userId>

Man kan altså sende inn roles og userId for å få personaliserte resultater (hvis userId så tar den også med brukerens personlige valg i forhold til skjulte meldinger / likte meldinger. Har bare brukt et søke-plugin for mongo, så det er altså ikke noe solr søk, så det tolker ikke søkeordet hvis man har skrevet feil, stemming osv.

Har lagt inn en dyplenke for melding, slik at man skal kunne klikke seg meldingen fra søkeresultat også.

Har vi fått på plass alle tingene dere trengte nå eller?
