### ISSUE TITLE
proxy-error

### ISSUE THREAD

**Issue by zrrrzzt** [telemark/portalen-forside#48]
Får ikke logget inn hverken i prod eller dev nå. Får proxyerror og noe som kan se ut som en unresolved promise

**Comment by zrrrzzt** [comment]
kan se ut til at det er noe porttrøbbel på 3030. f.eks. funker ikke :3030/api/ping men dersom man setter apiport til f.eks. 8888 så funker  :8888/api/ping helt fint

**Comment by anderswr** [comment]
Hey, er det noe bak våre låser og slåer?  Så kan eg fikse 🎱

**Comment by zrrrzzt** [comment]
Nope @anderswr tror dette kun hadde betydning lokalt. Ser ut til at ting er på plass i produksjon igjen

**Comment by zrrrzzt** [comment]
Klarer ikke gjenskape dette nå, så det kan ha vært noe som har hengt igjen lokalt
