### ISSUE TITLE
Lenker: Ved legg til/endre lenke må man oppfriske siden

### ISSUE THREAD

**Issue by maccyber** [telemark/portalen-forside#63]
Etter man har lagt til eller endret en lenke, må man oppfriske siden for å se endringen.

**Comment by gerhardsletten** [comment]
De skal oppdateres umiddelbart, eller suksessfull lagring. Kan det være noe annet som skjer hos deg som gjør at det feiler. Sjekk konsoll om du får noen feilmeldinger?

**Comment by maccyber** [comment]
Etter oppdatering ser det ut til å funke.
